apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-argo-app.fullname" . }}-configmap
  namespace: {{ .Values.Namespace }}
data:
  index.html: |
    <h1>Welcome to Helm with ConfigMap in ArgoCD</h1>
